coverage:
  status:
    project:
      unit:
        target: 60%
        flags:
          - unitTest
      integration:
        target: 60%
        flags:
          - integrationTest
flags:
  unitTest:
    paths:
      - potato-onetake-api/src/main/java/potato/onetake
  integrationTest:
    paths:
      - potato-onetake-api/src/main/java/potato/onetake
